export type EventDefinition = {
  key: string;
  category: string;
  label: string;
  description: string;
  noisy?: boolean;
};

export const EVENT_CATALOG: EventDefinition[] = [
  { key: 'member.join', category: 'Utenti', label: 'Ingresso utente', description: 'Un membro entra nel server.' },
  { key: 'member.leave', category: 'Utenti', label: 'Uscita utente', description: 'Un membro lascia il server.' },
  { key: 'member.update', category: 'Utenti', label: 'Modifica membro', description: 'Nickname, ruoli, timeout o altri dati membro cambiano.' },
  { key: 'moderation.kick', category: 'Moderazione', label: 'Kick', description: 'Un membro viene espulso.' },
  { key: 'moderation.ban', category: 'Moderazione', label: 'Ban', description: 'Un utente viene bannato.' },
  { key: 'moderation.unban', category: 'Moderazione', label: 'Unban', description: 'Un ban viene rimosso.' },
  { key: 'message.create', category: 'Messaggi', label: 'Messaggio creato', description: 'Un nuovo messaggio viene inviato.', noisy: true },
  { key: 'message.edit', category: 'Messaggi', label: 'Messaggio modificato', description: 'Il contenuto o gli allegati di un messaggio cambiano.' },
  { key: 'message.delete', category: 'Messaggi', label: 'Messaggio eliminato', description: 'Un messaggio viene eliminato.' },
  { key: 'message.bulk_delete', category: 'Messaggi', label: 'Eliminazione multipla', description: 'Più messaggi vengono eliminati insieme.' },
  { key: 'reaction.add', category: 'Reazioni', label: 'Reaction aggiunta', description: 'Viene aggiunta una reaction.', noisy: true },
  { key: 'reaction.remove', category: 'Reazioni', label: 'Reaction rimossa', description: 'Viene rimossa una reaction.', noisy: true },
  { key: 'reaction.clear', category: 'Reazioni', label: 'Reaction cancellate', description: 'Le reaction di un messaggio vengono cancellate.' },
  { key: 'reaction.emoji_clear', category: 'Reazioni', label: 'Emoji reaction rimossa', description: 'Tutte le reaction di una specifica emoji vengono rimosse.' },
  { key: 'poll.vote_add', category: 'Messaggi', label: 'Voto poll aggiunto', description: 'Un utente vota una risposta di un poll.', noisy: true },
  { key: 'poll.vote_remove', category: 'Messaggi', label: 'Voto poll rimosso', description: 'Un utente rimuove un voto da un poll.', noisy: true },
  { key: 'voice.join', category: 'Vocale', label: 'Ingresso vocale', description: 'Un utente entra in un canale vocale.' },
  { key: 'voice.leave', category: 'Vocale', label: 'Uscita vocale', description: 'Un utente esce dal vocale.' },
  { key: 'voice.move', category: 'Vocale', label: 'Spostamento vocale', description: 'Un utente cambia canale vocale.' },
  { key: 'voice.state', category: 'Vocale', label: 'Stato vocale', description: 'Cambiano mute, deaf, streaming o video.' },
  { key: 'voice.effect', category: 'Vocale', label: 'Effetto vocale', description: 'Viene inviato un effetto o suono in un canale vocale.', noisy: true },
  { key: 'voice.server_update', category: 'Vocale', label: 'Voice server aggiornato', description: 'Discord aggiorna l’endpoint del voice server senza salvare il token.', noisy: true },
  { key: 'role.create', category: 'Ruoli', label: 'Ruolo creato', description: 'Viene creato un ruolo.' },
  { key: 'role.update', category: 'Ruoli', label: 'Ruolo modificato', description: 'Viene modificato un ruolo.' },
  { key: 'role.delete', category: 'Ruoli', label: 'Ruolo eliminato', description: 'Viene eliminato un ruolo.' },
  { key: 'channel.create', category: 'Canali', label: 'Canale creato', description: 'Viene creato un canale.' },
  { key: 'channel.update', category: 'Canali', label: 'Canale modificato', description: 'Viene modificato un canale o i suoi permessi.' },
  { key: 'channel.delete', category: 'Canali', label: 'Canale eliminato', description: 'Viene eliminato un canale.' },
  { key: 'channel.pins', category: 'Canali', label: 'Pin modificati', description: 'La lista dei messaggi fissati di un canale cambia.' },
  { key: 'thread.create', category: 'Thread', label: 'Thread creato', description: 'Viene creato un thread o post forum.' },
  { key: 'thread.update', category: 'Thread', label: 'Thread modificato', description: 'Un thread viene modificato, archiviato o sbloccato.' },
  { key: 'thread.delete', category: 'Thread', label: 'Thread eliminato', description: 'Viene eliminato un thread.' },
  { key: 'thread.members_update', category: 'Thread', label: 'Membri thread modificati', description: 'Utenti entrano o escono da un thread.', noisy: true },
  { key: 'thread.member_update', category: 'Thread', label: 'Membro thread modificato', description: 'Cambiano i dati di appartenenza a un thread.', noisy: true },
  { key: 'thread.list_sync', category: 'Thread', label: 'Sincronizzazione thread', description: 'Discord sincronizza i thread accessibili al client.', noisy: true },
  { key: 'emoji.create', category: 'Espressioni', label: 'Emoji creata', description: 'Viene aggiunta una emoji.' },
  { key: 'emoji.update', category: 'Espressioni', label: 'Emoji modificata', description: 'Viene modificata una emoji.' },
  { key: 'emoji.delete', category: 'Espressioni', label: 'Emoji eliminata', description: 'Viene eliminata una emoji.' },
  { key: 'sticker.create', category: 'Espressioni', label: 'Sticker creato', description: 'Viene aggiunto uno sticker.' },
  { key: 'sticker.update', category: 'Espressioni', label: 'Sticker modificato', description: 'Viene modificato uno sticker.' },
  { key: 'sticker.delete', category: 'Espressioni', label: 'Sticker eliminato', description: 'Viene eliminato uno sticker.' },
  { key: 'invite.create', category: 'Inviti', label: 'Invito creato', description: 'Viene creato un invito.' },
  { key: 'invite.delete', category: 'Inviti', label: 'Invito eliminato', description: 'Viene eliminato un invito.' },
  { key: 'webhook.update', category: 'Webhook', label: 'Webhook modificati', description: 'Cambiano i webhook di un canale.' },
  { key: 'integration.update', category: 'Server', label: 'Integrazioni modificate', description: 'Cambiano le integrazioni collegate al server.' },
  { key: 'guild.update', category: 'Server', label: 'Server modificato', description: 'Cambiano nome, icona, banner o impostazioni del server.' },
  { key: 'guild.available', category: 'Sistema', label: 'Server disponibile', description: 'Il server torna disponibile al client Discord.', noisy: true },
  { key: 'guild.unavailable', category: 'Sistema', label: 'Server non disponibile', description: 'Discord segnala temporaneamente il server come non disponibile.' },
  { key: 'guild.remove', category: 'Sistema', label: 'Bot rimosso dal server', description: 'Il bot perde accesso al server o viene rimosso.' },
  { key: 'scheduled.create', category: 'Eventi', label: 'Evento creato', description: 'Viene creato un evento programmato.' },
  { key: 'scheduled.update', category: 'Eventi', label: 'Evento modificato', description: 'Viene modificato un evento programmato.' },
  { key: 'scheduled.delete', category: 'Eventi', label: 'Evento eliminato', description: 'Viene eliminato un evento programmato.' },
  { key: 'scheduled.user_add', category: 'Eventi', label: 'Interesse evento aggiunto', description: 'Un utente si iscrive a un evento programmato.', noisy: true },
  { key: 'scheduled.user_remove', category: 'Eventi', label: 'Interesse evento rimosso', description: 'Un utente si disiscrive da un evento programmato.', noisy: true },
  { key: 'automod.rule_create', category: 'AutoMod', label: 'Regola AutoMod creata', description: 'Viene creata una regola AutoMod.' },
  { key: 'automod.rule_update', category: 'AutoMod', label: 'Regola AutoMod modificata', description: 'Viene modificata una regola AutoMod.' },
  { key: 'automod.rule_delete', category: 'AutoMod', label: 'Regola AutoMod eliminata', description: 'Viene eliminata una regola AutoMod.' },
  { key: 'automod.action', category: 'AutoMod', label: 'Azione AutoMod', description: 'Una regola AutoMod viene attivata.' },
  { key: 'stage.create', category: 'Stage', label: 'Stage creato', description: 'Viene aperta una Stage instance.' },
  { key: 'stage.update', category: 'Stage', label: 'Stage modificato', description: 'Viene modificata una Stage instance.' },
  { key: 'stage.delete', category: 'Stage', label: 'Stage chiuso', description: 'Viene chiusa una Stage instance.' },
  { key: 'soundboard.create', category: 'Soundboard', label: 'Suono creato', description: 'Viene aggiunto un suono alla soundboard.' },
  { key: 'soundboard.update', category: 'Soundboard', label: 'Suono modificato', description: 'Viene modificato un suono della soundboard.' },
  { key: 'soundboard.delete', category: 'Soundboard', label: 'Suono eliminato', description: 'Viene eliminato un suono dalla soundboard.' },
  { key: 'soundboard.sync', category: 'Soundboard', label: 'Soundboard sincronizzata', description: 'Discord aggiorna l’elenco dei suoni del server.', noisy: true },
  { key: 'interaction.create', category: 'Interazioni', label: 'Interazione bot', description: 'Un utente usa un comando, bottone, menu o modal del bot.', noisy: true },
  { key: 'application.permissions_update', category: 'Applicazioni', label: 'Permessi comando applicazione', description: 'Cambiano i permessi di un comando o entita applicazione nel server.' },
  { key: 'user.update', category: 'Utenti', label: 'Profilo utente modificato', description: 'Cambiano username, avatar o altri dati globali di un utente.', noisy: true },
  { key: 'audit.entry', category: 'Audit', label: 'Audit log Discord', description: 'Discord genera una nuova voce di Audit Log.', noisy: true },
  { key: 'presence.update', category: 'Presenza', label: 'Presenza modificata', description: 'Status o attività di un membro cambiano.', noisy: true },
  { key: 'typing.start', category: 'Presenza', label: 'Typing', description: 'Un utente inizia a scrivere.', noisy: true },
  { key: 'raw.gateway', category: 'Avanzato', label: 'Gateway raw', description: 'Copia grezza degli eventi Gateway non normalizzati. Da usare solo per debug.', noisy: true },
  { key: 'system.ready', category: 'Sistema', label: 'Bot avviato', description: 'Il bot completa la connessione a Discord.' },
  { key: 'system.error', category: 'Sistema', label: 'Errore bot', description: 'Errore runtime del bot.' },
  { key: 'system.warn', category: 'Sistema', label: 'Warning bot', description: 'Warning emesso dal client Discord.', noisy: true }
];

export const eventDefinition = (key: string) => EVENT_CATALOG.find((event) => event.key === key);
